### ISSUE TITLE
PHP!?!?!?

### ISSUE THREAD

**Issue by TheDataLioness** [Mohagames205/quadratic_web#1]
Dit kun je MAKKELIJK met JS doen.
Waarom een pagina refresh als t nie nodig is.
Gebruik JS pls dankjewel =)
Ik ben zwaar triggered doe er wat mee anders ga ik janken ofs idk

**Comment by Mohagames205** [comment]
Mohamed kan geen JS, dus geen JS! 
Misschien een andere keer wanneer ik wel JS kan, maar ik ben nu te lui om JS te leren.

**Comment by Mohagames205** [comment]
ok ik ga in js proberen maken ok ok

**Comment by Mohagames205** [comment]
Check de [javascript branch](https://github.com/mohagames205/quadratic_web/tree/javascript) ok
